name: Create PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          working_directory: cv
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv/cv.pdf
          compression-level: 0 # don't compress PDF
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "test-release"
          artifacts: "cv/cv.pdf"
