name: Create PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv/cv.tex
      - name: Copy
        run: |
          mkdir output
          cp ./cv.pdf ./output/cv.pdf
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: output/cv.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: updated-${{ github.event.repository.updated_at }}
          release_name: Automated PDF build updated-${{ github.event.repository.updated_at }}
          draft: false
          prerelease: false
      - name: Upload Release
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: cv
          asset_path: output/cv.pdf
          asset_content_type: application/pdf
