name: Create PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Copy
        run: |
          mkdir output
          cp ./cv.pdf ./output/cv.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: cv
          path: output/cv.pdf
