name: Create PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          working_directory: cv
      - name: Copy
        run: |
          cp ./cv/cv.pdf ../cv.pdf
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: "test"
          files: |
            cv.pdf
