name: Lint TeX

on:
  push:
    branches: [ main, drafting ]
  pull_request:
    branches: [ main, drafting ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: ChkTeX Linter
        uses: j2kun/chktex-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
